name: node.js workflow

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs: 
  runs-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v1
    -uses: actions/setip-node@v2
      with:
        node-version:12
    -run: npm install
    -run: npm run start



